### ISSUE TITLE
Block namespace error

### ISSUE THREAD

**Issue by justinwhall** [ahmadawais/Gutenberg-Boilerplate#10] opened 2017-11-29 17:28 UTC
### Error
```
Block names must contain a namespace prefix, include only lowercase alphanumeric characters or dashes, and start with a letter. Example: my-plugin/my-custom-block
```

The [namespace](https://github.com/ahmadawais/Gutenberg-Boilerplate/blob/master/block/01-basic/block.js#L28) *is* alphanumeric. However, if I change the namespace from: 

`registerBlockType( 'gb/01-basic' ...` to `registerBlockType( 'gb/one-basic' ...` 

The error is resolved.

**Comment by justinwhall** [comment] 2017-11-29 17:30
In fact, `registerBlockType( 'gb/foo-01-basic'...` works as well. Gutenberg bug?

**Comment by justinwhall** [comment] 2017-11-29 17:44
Oh, I see. 

> ...and start with a letter...

Looks like the namespace needs to change.

**Comment by ahmadawais** [comment] 2017-11-29 18:51
Hey, @justinwhall 
Thanks for thinking of sending a PR on this repo.

I just tested this repo and it seems to be working fine. All code works without any error. Can you share with me what error are you looking at and steps to reproduce it before I go and change the codebase for (maybe) a change that we might not need?

Peace! ✌️

**Comment by justinwhall** [comment] 2017-11-29 19:40
1) Gutenberg 1.8.0
2) git clone git@github.com:ahmadawais/Gutenberg-Boilerplate.git into /plugins
3) Edit "Hello World" post
4) See `Block names must contain a namespace prefix, include only lowercase alphanumeric characters or dashes, and start with a letter. Example: my-plugin/my-custom-block
`
[This line](https://github.com/WordPress/gutenberg/blob/v1.8.0/blocks/api/registration.js#L58) returns false.

No match: [https://regex101.com/r/eqo5ZZ/1](https://regex101.com/r/eqo5ZZ/1)

However... Upgrading to 1.8.1 seems to resolve the issue. 🙃

**Comment by ahmadawais** [comment] 2017-12-03 01:08
Must be fixed now. Do confirm! 👋

**Closed as completed** 2017-12-03 01:08 UTC
